name: pharmaguard_app
description: "Projeto com flutter para aplicação de controle de medicamentos."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  workmanager: ^0.5.2
  permission_handler: ^10.2.0
  flutter_lints: ^4.0.0
  url_launcher: ^6.0.20
  http: ^0.13.3
  shared_preferences: ^2.0.15
  flutter_dotenv: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
